// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Library.Core.Model.Entities
{
    public partial class BookTitle
    {
        public BookTitle()
        {
            BookCopy = new HashSet<BookCopy>();
        }

        public int Id { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }

        public virtual ICollection<BookCopy> BookCopy { get; set; }
    }
}