// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Library.Core.Model.Entities
{
    public partial class BookCopy
    {
        public BookCopy()
        {
            Rental = new HashSet<Rental>();
        }

        public int Id { get; set; }
        public int BookTitleId { get; set; }

        public virtual BookTitle BookTitle { get; set; }
        public virtual ICollection<Rental> Rental { get; set; }
    }
}