// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Library.Core.Model.Entities
{
    public partial class Rental
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public DateTime DateRented { get; set; }
        public DateTime DateDue { get; set; }
        public DateTime? DateReturned { get; set; }
        public int BookCopyId { get; set; }

        public virtual BookCopy BookCopy { get; set; }
        public virtual User User { get; set; }
    }
}