// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Library.Core.Model.Entities
{
    public partial class UserContact
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Contact { get; set; }
        public string Type { get; set; }

        public virtual User User { get; set; }
    }
}