// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Library.Core.Model.Entities
{
    public partial class User
    {
        public User()
        {
            Rental = new HashSet<Rental>();
            UserContact = new HashSet<UserContact>();
        }

        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public DateTime DateOfBirth { get; set; }
        public int? MrzdataId { get; set; }

        public virtual Mrzdata Mrzdata { get; set; }
        public virtual ICollection<Rental> Rental { get; set; }
        public virtual ICollection<UserContact> UserContact { get; set; }
    }
}